language: php

php:
  - '7.3'

install:
  - phpenv config-rm xdebug.ini
  - pecl install uopz
  - cd ..
  - wget https://github.com/cmsimple-xh/cmsimple-xh/releases/download/1.7.2/CMSimple_XH-1.7.2.zip
  - unzip CMSimple_XH-1.7.2.zip
  - cp -R $TRAVIS_BUILD_DIR cmsimplexh/plugins/xhshop
  - cd cmsimplexh/plugins/xhshop
  - composer install
  - export PATH=vendor/bin:$PATH

script:
  - phing sniff
  - phing unit-tests
